config/routes.rb
Rails.application.routes.draw do
  
  root 'chatroom#index'
  get 'login', to: 'sessions#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true, length: { minimum: 3, maximu: 15 },
    uniqueness: { case_sensitive: false }
    has_many :messages
    has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
    def index
        @messages = Message.all
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="circular orange beer icon "></i>
  Honest Beer chat
</h4>
<div class = "ui two column grid"> 
    <div class= "twelve wide column">
        <div class="ui fluid raised card chatbox">
            <div class="content">
                <div class="ui feed">  
                    <%= render @messages %>
                </div>
            </div>
            <div class= "extra content">
                <form class="ui reply form">
                    <div class="field">
                        <div class="ui fluid icon input">
                            <input type="text" placeholder="Ener message...">
                            <i class="bordered inverted orange edit icon"></i>
                        </div>      
                    </div>

                </form>
             </div>
        </div>        
    </div>
    <div class= "four wide column">
        <div class="ui fluid raised card chatbox">
            <div class="content">

                <div class="ui inverted vertical menu">
                <a class="active item">
                    Home
                </a>
                <a class="item">
                    Messages
                </a>
                <a class="item">
                    Friends
                </a>
                </div>
            </div>    
        </div>        
    </div>
</div>

app/views/layouts/_navigation.html.erb
      <a class="item">
        Messages
      </a>
      <div class="right menu">
        <div class="ui dropdown item">
          Account <i class="dropdown icon"></i>
          <div class="menu">
            <a class="item">Log out</a>
            <%= link_to "Log in", login_path, class: "item" %>
            <a class="item">Sign up</a>
          </div>
        </div>
        <div class="item">
            <div class="ui primary button">Sign Up</div>
        </div>
      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Messageme</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  
  <body>
    
  </body>
    <div class="ui small inverted menu">
    <div class= "ui container"> 
      <%= link_to "Chatroom", root_path, class: "item" %>
      <%= render 'layouts/navigation' %>
    </div>
  </div>
  <div class = "ui container">
    <%= yield %>
  </div>
</html>

app/views/messages/_message.html.erb
<div class="event">
    <div class="content">
    <div class="summary">
        <em><%= message.user.username%> </em>: <%= message.body %>
    </div>
    </div>
</div>